"""new posts table

Revision ID: 4ebdd1f763e9
Revises: b0b732fe758a
Create Date: 2023-05-30 23:26:37.272977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebdd1f763e9'
down_revision = 'b0b732fe758a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('analise_instagram')
    
    with op.batch_alter_table('posts_instagram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_empresa', sa.String(length=64), nullable=True))
        batch_op.alter_column('id_empresa',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('caption',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_posts_instagram_id_empresa'), ['id_empresa'], unique=False)
     

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts_instagram', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'empresa', ['id_empresa'], ['id'])
        batch_op.drop_index(batch_op.f('ix_posts_instagram_id_empresa'))
        batch_op.alter_column('caption',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.String(length=64),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('id_empresa',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('nome_empresa')

    with op.batch_alter_table('post_instagram', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'empresa', ['id_empresa'], ['id'])
        batch_op.drop_index(batch_op.f('ix_post_instagram_id_empresa'))
        batch_op.alter_column('nome_empresa',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('caption',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.String(length=64),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('id_empresa',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)

#     op.create_table('analise_instagram',
#     sa.Column('id', sa.INTEGER(), nullable=False),
#     sa.Column('id_empresa', sa.INTEGER(), nullable=False),
#     sa.Column('analise', sa.TEXT(), nullable=False),
#     sa.Column('data_criacao', sa.DATETIME(), nullable=True),
#     sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
#     sa.PrimaryKeyConstraint('id')
#     )
    # ### end Alembic commands ###
