"""empty message

Revision ID: 8cf331cfbde3
Revises: 4ebdd1f763e9
Create Date: 2023-05-30 23:48:18.801394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf331cfbde3'
down_revision = '4ebdd1f763e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_instagram', schema=None) as batch_op:
        batch_op.alter_column('id_empresa',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('caption',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('nome_empresa',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_post_instagram_id_empresa'), ['id_empresa'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('posts_instagram', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts_instagram', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'empresa', ['id_empresa'], ['id'])

    with op.batch_alter_table('post_instagram', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'empresa', ['id_empresa'], ['id'])
        batch_op.drop_index(batch_op.f('ix_post_instagram_id_empresa'))
        batch_op.alter_column('nome_empresa',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('caption',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.String(length=64),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('id_empresa',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
